#!/usr/bin/ruby
# encoding: utf-8

$:.push("./lib")
require "optipng"
require "em-pipe-run"

EM::run do
    puts Optipng.available?.inspect
    Optipng.optimize(["1.png", "4.png", "mp.png"], :level => 7, :debug => true) do |result|
        puts result.inspect
    end
    
    puts "xxx"
end
